### PR TITLE
Fixed Errors, added clear methods

### PR DESCRIPTION
**Pull request by Arthelon**
This PR introduces the following changes:
- Updates buffertools dep version which otherwise causes an error
- Adds check to ignore undefined strip slots while refreshing strip data
- Adds .clear() method to PixelStrip, which sets all pixels to color (0, 0, 0, 0), and .clearStrips() to the PixelPusher controller which clears every strip on the controller.

### CODE REVIEW

**Comment by bo01ean** [comment]
You can actually remove buffertools altogether. 

a.equals(b) is faster and Buffer.toString() === Buffer.toString() runs similarly:

`  test Buffer.compare.BUFFERTOOLS#test x 1,292 ops/sec ±7.59% (65 runs sampled) +6s
  test Buffer.compare.TOSTRING#test x 1,336 ops/sec ±5.45% (84 runs sampled) +6s
  test Buffer.equals.#test x 1,327 ops/sec ±1.91% (69 runs sampled) +6s
  test Fastest is Buffer.equals.#test,Buffer.compare.BUFFERTOOLS#test +5ms`
with Buffer(2550)

Both methods are native :)

**Comment by koopero** [comment]
@ajones Are you accepting PRs for this project? The current buffertools dep is broken, making installation impossible (for me, anyway).

**Comment by robot-head** [comment]
Sorry I'll take the PR

**Comment by robot-head** [comment]
Yes, sorry.  I'll review

**Comment by koopero** [comment]
Thanks for your prompt reply, @robot-head 
If you're going to keep using buffertools, it's up to 2.1.6 now.
I like @bo01ean 's suggestion of removing it entirely, though. Anything I can do to help?

**Comment by robot-head** [comment]
I realized I'm not the owner of this repo lol.  I am down to remove it
entirely, seems okay to me.

**Comment by koopero** [comment]
Created [new PR](https://github.com/ajones/node-pixelpusher/pull/3) with changes from this branch, removal of buffertools and updates to Buffer.alloc

**Comment by Arthelon** [comment]
I hope @ajones still maintains this repository. His Github history looks pretty quiet. If he doesn't get back to your PR in two weeks I'll shoot him an email.

**Comment by ajones** [comment]
Hey guys! apologies. I am still here every day just on private projects :) I haven't touched this code in sooooooooooo long. Excited to hear about what you are making!

**Comment by koopero** [comment]
No worries, bud! Thanks for your hard work on this project. I look forward to integrating it. Maybe drop a comment here when you update npm.

**Comment by ajones** [comment]
@koopero I just pulled and updated the dependencies for `buffertools`. I updated my local node ver to 11.4 ran an audit and outdated and nothing else came back with warnings. 
LMK if after you pull you are having any issues and we can get them solved.

**Comment by koopero** [comment]
@ajones Pulled down the latest. `buffertools` 2.1.6 compiles successfully ( although with warnings ) on node v11.3.0 on OSX 10.14. 

I would still recommend merging #3 , as it removes fragile gyp compilation entirely, as well as squelching these warnings:

```
(node:15542) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by ajones** [comment]
@koopero I dont know how I missed that PR, apologies. I just merged it in

**Pull request merged**
